export const FIRSTNAME_TITLE = 'Name:'
export const LASTNAME_TITLE = 'Lastname:'
export const CATEGORY_TITLE = 'Category:'
export const AMOUNT_TITLE = 'Amount of jokes:'
export const FETCH_BUTTON = 'Get jokes'
export const TOTAL_TAG = 'total: '
